[[pages]]
path = "streamlit_main.py"
name = "News Summarizer"
icon = "ğŸ“°"

[[pages]]
path = "pages/weatherAlerts.py"
name = "Weather Alerts"
icon = "ğŸŒ¤ï¸"

[[pages]]
path = "pages/newsletter.py"
name = "Sample Newsletter"
icon = "ğŸ“©"

[[pages]]
path = "pages/talking_points.py"
name = "Talking Points"
icon = "ğŸ—ï¸"

[[pages]]
path = "pages/company_updates.py"
name = "Company Updates"
icon = "ğŸ“Š"