[[pages]]
path = "streamlit_main.py"
name = "News Summarizer"
icon = "ğŸ“°"

[[pages]]
path = "pages/weatherAlerts.py"
name = "Weather Alerts"
icon = "ğŸŒ¤ï¸"

[[pages]]
path = "pages/newsletter.py"
name = "Sample Newsletter"
icon = "ğŸ“©"
